### ISSUE TITLE
Outdated `inverseSHT` header documentation

### ISSUE THREAD

**Issue by HaHeho** [polarch/Spherical-Harmonic-Transform#5]
The documentation of the `inverseSHT` function parameters is very confusing and should be updated, if possible. :)

https://github.com/polarch/Spherical-Harmonic-Transform/blob/c3c74194c87025529af8602d88adcbeeed963485/inverseSHT.m#L1-L11

**Comment by polarch** [comment]
Well said :-) ! Updated to at least reflect something about arguments and output. I hope it helps.
